version: '3'
services:
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: dSiwe923JDsiqpoXoiwe23
            MYSQL_DATABASE: pdf_system
        volumes:
            - db_data:/var/lib/mysql
    frontend:
        build: 
            context: .
            dockerfile: Dockerfile.frontend
        ports:
            - "3000:3000"
        volumes:
            - ./front-end/pdf-app:/app
    api:
        build: 
            context: .
            dockerfile: Dockerfile.api
        ports:
            - "8000:8000"
        depends_on:
            - db
        env_file:
            - .env
        environment:
            ENGINE: mysql
            ADAPTER: pymysql
            ASYNC_ADAPTER: aiomysql
            DB_NAME: pdf_system
            TEST_DB_NAME: test_pdf_system
            HOSTNAME: localhost
            SECRET_KEY: your_secret_key
            ALGORITHM: HS256
            ACCESS_TOKEN_EXPIRE_MINUTES: 60
            USERNAME: root
            PASSWORD: dSiwe923JDsiqpoXoiwe23
        volumes:
            - ./back-end:/app
volumes:
    db_data: