# Start from a base Python image
FROM python:3.12

# Set a working directory
WORKDIR /app

# Copy the requirements.txt and main.py, and install the Python dependencies
COPY requirements.txt ./ 
COPY ./back-end /app
RUN pip install -r requirements.txt

# Expose the necessary port
EXPOSE 8000

# Set the command that will be executed when the Docker container starts
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]