services:
    db:
        image: mysql:8.3.0
        command: 
            - /bin/sh
            - -c
            - |
                exec mysqld --init-file /data/application/init.sql --pid-file=/var/lib/mysql/mysqld.pid
        volumes:
            - db_data:/var/lib/mysql
            - ./init.sql:/data/application/init.sql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        ports:
            - "3307:3306"
    frontend:
        build: 
            context: .
            dockerfile: Dockerfile.frontend
        ports:
            - "5000:5000"
        volumes:
            - ./front-end/pdf-app:/app
    api:
        build: 
            context: .
            dockerfile: Dockerfile.api
        ports:
            - "8000:8000"
        depends_on:
            - db
        env_file:
            - .env
        environment:
            ENGINE: ${ENGINE}
            ADAPTER: ${ADAPTER}
            ASYNC_ADAPTER: ${ASYNC_ADAPTER}
            DB_NAME: ${DB_NAME}
            TEST_DB_NAME: ${TEST_DB_NAME}
            HOSTNAME: db
            MYSQL_HOSTNAME: db
            SECRET_KEY: ${SECRET_KEY}
            ALGORITHM: ${ALGORITHM}
            ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./back-end:/app
volumes:
    db_data: